# ==== Model ====
model = "rnn"
input_dim = 3
hidden_dim = 64
output_dim = 5

# ==== Data ====
seq_len = 30
horizon = 1
dataset_size = 1000

# ==== Training ====
epochs = 10
batch_size = 32
lr = 0.001
loss = "mse"
metric = "mae"
optimizer = "adam"
patience = 50

# ==== Misc ====
force_cpu = false